export CILK_NWORKERS=1
./aug_sum 0 > aug.txt
./aug_sum 0 >> aug.txt
./aug_sum 1 >> aug.txt
./aug_sum 1 >> aug.txt
./aug_sum 2 >> aug.txt
./aug_sum 2 >> aug.txt
./aug_sum 3 >> aug.txt
./aug_sum 3 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 7 >> aug.txt
./aug_sum 7 >> aug.txt
export CILK_NWORKERS=2
./aug_sum 3 >> aug.txt
./aug_sum 3 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 7 >> aug.txt
./aug_sum 7 >> aug.txt
export CILK_NWORKERS=4
./aug_sum 3 >> aug.txt
./aug_sum 3 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 7 >> aug.txt
./aug_sum 7 >> aug.txt
export CILK_NWORKERS=8
./aug_sum 3 >> aug.txt
./aug_sum 3 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 7 >> aug.txt
./aug_sum 7 >> aug.txt
export CILK_NWORKERS=16
./aug_sum 3 >> aug.txt
./aug_sum 3 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 8 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 4 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 5 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 6 >> aug.txt
./aug_sum 7 >> aug.txt
./aug_sum 7 >> aug.txt
